services:
  app:
    image: ${DOCKER_IMAGE:-46112/routine-it-backend}:${DEPLOY_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: routine-app
    ports:
      - "${APP_PORT}:8080"
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JPA_HIBERNATE_DDL_AUTO=${JPA_HIBERNATE_DDL_AUTO}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - OAUTH_CALLBACK_URI=${OAUTH_CALLBACK_URI}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - LOG_LEVEL_SQL=${LOG_LEVEL_SQL}
      - LOG_LEVEL_SQL_BIND=${LOG_LEVEL_SQL_BIND}
      - LOG_LEVEL_APP=${LOG_LEVEL_APP}
      - SPRING_TASK_SCHEDULING_POOL_SIZE=${SCHEDULER_POOL_SIZE}
      - SCHEDULER_MONTHLY_ENABLED=${MONTHLY_SCHEDULER_ENABLED}
      - SCHEDULER_RETRY_ENABLED=${RETRY_SCHEDULER_ENABLED}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    depends_on:
      - db
      - redis
    networks:
      - routine-network
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: routine-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - routine-network
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: routine-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - routine-network
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

volumes:
  mysql-data:
  redis-data:

networks:
  routine-network:
    driver: bridge