name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build even without code changes'
        required: false
        default: true
        type: boolean

env:
  DOCKER_IMAGE: 46112/routine-it-backend
  DOCKER_TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    if: github.repository == 'Goorda-Goormi/routine-it-spring-be'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build application
        env:
          SPRING_PROFILES_ACTIVE: docker
        run: ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
            ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Generate deployment tag
        id: tag
        run: |
          TAG="${{ env.DOCKER_TAG }}-$(date +%Y%m%d-%H%M%S)-$(echo ${{ github.sha }} | cut -c1-7)"
          echo "deployment_tag=$TAG" >> $GITHUB_OUTPUT
          echo "🏷️ Deployment tag: $TAG"

      - name: Create release notes
        id: release_notes
        run: |
          NOTES="## 🚀 Deployment: ${{ steps.tag.outputs.deployment_tag }}
          
          ### Changes
          - **Branch**: ${{ github.ref_name }}
          - **Commit**: ${{ github.sha }}
          - **Author**: ${{ github.actor }}
          - **Docker Image**: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          
          ### Quick Deploy Commands
          \`\`\`bash
          # Pull latest image
          docker pull ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          
          # Update deployment
          docker-compose down && docker-compose pull && docker-compose up -d
          \`\`\`"
          
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-info-${{ steps.tag.outputs.deployment_tag }}
          path: |
            build/libs/*.jar
            docker-compose.yml
            .env.example
          retention-days: 30