name: Test SSH Connection

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/test-ssh-connection.yml'
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test SSH Setup
        run: |
          echo "🔐 Setting up SSH..."
          mkdir -p ~/.ssh
          
          # Base64로 인코딩된 키를 디코드 (한 줄로 된 Base64)
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d ' ' | base64 -d > ~/.ssh/routine-it-key.pem
          
          # 권한 설정
          chmod 600 ~/.ssh/routine-it-key.pem
          
          # SSH 키 형식 검증
          echo "📋 Key format check:"
          echo "First line:"
          head -n 1 ~/.ssh/routine-it-key.pem
          echo "Last line:"
          tail -n 1 ~/.ssh/routine-it-key.pem
          echo "Total lines:"
          wc -l ~/.ssh/routine-it-key.pem
          
          # SSH 연결 테스트 (상세 로그 포함)
          echo "🧪 Testing SSH connection with verbose mode..."
          ssh -vvv -i ~/.ssh/routine-it-key.pem \
              -o StrictHostKeyChecking=no \
              -o ConnectTimeout=10 \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "echo '✅ SSH connection successful! Hostname: \$(hostname)'" || {
            echo "❌ SSH connection failed"
            echo "Debug information:"
            echo "- Host: ${{ secrets.EC2_HOST }}"
            echo "- User: ${{ secrets.EC2_USER }}"
            echo "- Key file exists: $(test -f ~/.ssh/routine-it-key.pem && echo 'Yes' || echo 'No')"
            echo "- Key file permissions: $(ls -la ~/.ssh/routine-it-key.pem)"
            echo ""
            echo "📝 Troubleshooting tips:"
            echo "1. Make sure EC2_SSH_PRIVATE_KEY is Base64 encoded"
            echo "2. Verify EC2_USER is 'ec2-user' (not 'ubuntu')"
            echo "3. Verify EC2_HOST is correct (54.180.93.1)"
            echo "4. Check if the EC2 security group allows SSH from GitHub Actions IPs"
            exit 1
          }
          
          echo "🎉 SSH test completed successfully!"